# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BGSecret' do
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!
pod 'SwiftKeychainWrapper', '3.2.0', :inhibit_warnings => true
pod 'RNCryptor', '5.0.3', :inhibit_warnings => true
# Pods for BGSecret

end
